import './globals.css'
import type { Metadata } from 'next'
import { Roboto, Inter } from 'next/font/google'
import localFont from 'next/font/local'
import NavBar from './NavBar'
import { Suspense } from 'react'
import AuthProvider from './auth/Provider'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500'] })
const comicNeue = localFont({
  src: '../public/fonts/ComicNeue-Regular.ttf',
  variable: '--font-comicneue'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  // social media metatags
  openGraph: {
    title: '...',
    description: '...'
  }
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter">
      <AuthProvider>
        <body className={comicNeue.variable}>
          <NavBar />
          <main className='p-5'>
              {children}
          </main>
        </body>
      </AuthProvider>
    </html>
  )
}
